[env:inkplate5]
platform = espressif32
board = esp32dev
framework = arduino
board_build.f_cpu = 240000000L
board_build.partitions = min_spiffs.csv
board_build.f_flash = 80000000L
board_build.flash_mode = qio

lib_extra_dirs = lib
lib_deps =
    SdFat
    U8g2_for_Adafruit_GFX
    Adafruit GFX Library
    Adafruit BusIO
build_flags =
    -DARDUINO_INKPLATE5V2
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DINKPLATE_5V2
    -DSCREEN_WIDTH=800
    -DSCREEN_HEIGHT=600
    -Os
    -DIZE_INKPLATE_MINIMAL_IMAGE=1
    -DIZE_ENABLE_DIRECT_GITHUB_SYNC=1
    -DIZE_ENABLE_BLE_KEYBOARD=0
    -DCORE_DEBUG_LEVEL=0

monitor_speed = 921600
upload_speed = 921600
